name: Check Docker Build

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Pull Request to Master
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          base: master
          branch: ${{ steps.extract_branch.outputs.branch }}
          delete-branch: false
          title: '[Docker] Automated PR to push/build enedisgateway:latest'
          body: |
            Automated PR to push/build enedisgateway:latest
          labels: |
            automated_pullrequest
          assignees: m4dm4rtig4n
          reviewers: m4dm4rtig4n
          team-reviewers: |
            owners
            maintainers
          draft: false